-- MySQL Script generated by MySQL Workbench
-- sáb 24 jun 2017 23:24:43 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sabolsas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sabolsas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sabolsas` DEFAULT CHARACTER SET utf8 ;
USE `sabolsas` ;

-- -----------------------------------------------------
-- Table `sabolsas`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sabolsas`.`Aluno` (
  `id` INT(11) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `matricula` INT(11) NOT NULL,
  `cr` FLOAT NOT NULL,
  `data_entrada` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sabolsas`.`Orientador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sabolsas`.`Orientador` (
  `id` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `matricula` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sabolsas`.`aluno_orientador_mm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sabolsas`.`aluno_orientador_mm` (
  `id` INT NOT NULL,
  `aluno_id` INT NOT NULL,
  `orientador_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
